# np_03 : Multidimensional-Indexing-and-Axis

In [1]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])


In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [4]:
arr[0][2]

3

In [5]:
arr[0:2, 1:3]
# 0:2 for rows 0 & 1
# 1:3 for columns 1 &2

array([[2, 3],
       [5, 6]])

In [6]:
arr3D = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    
[[7, 8, 9],
 [10, 11, 12]]

])

In [7]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [8]:
arr3D[:, 0, :] = 0

In [9]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])

#### 0- axis : traversing elements of a row alog columns ( ↕ : vertical traversal)

#### 1- axis : traversing elements of columns along rows (↔ : horizontal traversal) 

#### 3-D array is just like notebook with multiple pages where each page is an 2-D array and whole notebook combined is 3-D array