# Exercises for Practice
- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.

### 1. Create a 3×3 array filled with random numbers and print its shape

In [4]:
import numpy as np

In [5]:
arr0 = np.random.rand(3,3)
print(arr0)

[[0.10832159 0.95319388 0.23753315]
 [0.09344066 0.95981471 0.66377673]
 [0.09072012 0.21052298 0.52958279]]


### 2. Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [7]:
arr1 = arr0.astype(int)
print(arr1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]

In [9]:
nums = np.array([[1, 2, 3] ,[4, 5, 6],[7, 8, 9]])
#even_nums = nums[nums % 2 == 0]
n = np.array([1, 2, 3, 4, 5, 6])
even_n = n[[1, 3, 5]]
print("EVen_n: in 1D array", even_n)
even_nums = nums[[0, 1, 1, 2], [1, 0, 2, 1]]
print("Even_nums in 3X3 multi_D array:", even_nums)

EVen_n: in 1D array [2 4 6]
Even_nums in 3X3 multi_D array: [2 4 6 8]


### 4. Reshape a 1D array of size 9 into a 3×3 matrix.

In [11]:
print(nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
flattened_arr = nums.flatten()
print(flattened_arr)

[1 2 3 4 5 6 7 8 9]


In [13]:
print(nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
nums = nums.ravel()  # returns a view of nums instead of the copy
print(nums)

[1 2 3 4 5 6 7 8 9]


In [15]:
print("flattened_nums to 3X3 nums_array:\n", np.reshape(nums,(3,3)))

flattened_nums to 3X3 nums_array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### 5. Use boolean masking to filter numbers greater than 50 in an array.

In [17]:
arr_50 = np.array([[12,65,84], [76,22,2], [7,43,99]])
print(arr_50[arr_50 > 50])

[65 84 76 99]
